Allow project reference from vanilla classlib
rr-wfm/MSBuild.Sdk.SqlProj pull request #189
Opened 2021-09-11 23:18 UTC by AroglDarthu

This solves #117 

Take care to add `<ReferenceOutputAssembly>False</ReferenceOutputAssembly>` to the project reference. Without it, the compilation of the vanilla class library will fail; a `.dacpac` file is not a valid assembly ;-)

The target `GetCopyToOutputDirectoryItems` returns an `AllItemsFullPathWithTargetPath` item collection. The new target `CopyDacpacs` runs before `GetCopyToOutputDirectoryItems` and preloads `AllItemsFullPathWithTargetPath` with all `.dacpac` files found in the intermediate output path (they are not copied to the bin folder yet).

Currently this solution does not copy any referenced dacpac files, other then the ones referenced via a (nested) project reference. Perhaps it would be wise to also add the `@(DacpacReference)` list?

2021-09-13 07:11 UTC, jmezach requested changes

2021-09-13 07:11 UTC, jmezach commented on src/MSBuild.Sdk.SqlProj/Sdk/Sdk.targets
> +  <Target Name="CopyDacpacs" BeforeTargets="GetCopyToOutputDirectoryItems">
We should probably add some comments here explaining what this target is for for future reference.

2021-09-13 07:11 UTC, jmezach commented on test/TestIncludeFromVanillaProj/TestIncludeFromVanillaProj.csproj
> +        <ReferenceOutputAssembly>False</ReferenceOutputAssembly>
I believe we can have the `ReferenceOutputAssembly` as an attribute on the `ProjectReference` element as well which is a bit cleaner IMHO.

2021-09-13 07:11 UTC, jmezach commented on test/TestIncludeFromVanillaProj/TestIncludeFromVanillaProj.csproj
> +        <ReferenceOutputAssembly>False</ReferenceOutputAssembly>
We should probably explain this in the README as well.

2021-09-14 06:50 UTC, jmezach approved these changes
LGTM. Perhaps @ErikEJ and @jeffrosenberg could have a look at this as well.

2021-09-14 13:43 UTC, ErikEJ commented on README.md
> +      Include="../MyDacpacProj/MyDacpacProj.csproj"
Should it be ".sqlproj" ??

2021-09-14 13:45 UTC, ErikEJ approved these changes

2021-09-14 13:47 UTC, jmezach approved these changes

2021-09-14 13:47 UTC, jmezach commented
Let's get this merged!

2021-09-14 13:47 UTC, merged